
' write the _filterresults.asp page
Set sp = fs.CreateTextFile(TheFullPath & "\" & ProjectName & "_filterresults.asp", True)

sp.WriteLine(Chr(60) + Chr(37) + "@ LANGUAGE=VBScript" + chr(37) + ">")
sp.WriteLine("")
sp.WriteLine(Chr(60) + Chr(37))
sp.WriteLine("'---- CursorTypeEnum Values ----")
sp.WriteLine("Const adOpenForwardOnly = 0")
sp.WriteLine("Const adOpenKeyset = 1")
sp.WriteLine("Const adOpenDynamic = 2")
sp.WriteLine("Const adOpenStatic = 3")
sp.WriteLine("'---- LockTypeEnum Values ----")
sp.WriteLine("Const adLockReadOnly = 1")
sp.WriteLine("Const adLockPessimistic = 2")
sp.WriteLine("Const adLockOptimistic = 3")
sp.WriteLine("Const adLockBatchOptimistic = 4")
sp.WriteLine("'---- CommandTypeEnum Values ----")
sp.WriteLine("Const adCmdUnknown = &H0008")
sp.WriteLine("Const adCmdText = &H0001")
sp.WriteLine("Const adCmdTable = &H0002")
sp.WriteLine("Const adCmdStoredProc = &H0004")
sp.WriteLine("Const adCmdFile = &H0100")
sp.WriteLine("Const adCmdTableDirect = &H0200")
sp.WriteLine("Server.ScriptTimeout = 600")

sp.WriteLine("'---Set Max Records and Number of Rows Displayed")
sp.WriteLine("maxRecs = " & objRS2("MaxRecords"))
sp.WriteLine("DisplayRows = " & objRS2("MaxRows"))
sp.WriteLine("'Test to see if the " + chr(34) + "New Query" + chr(34) + " button was clicked")
sp.WriteLine("	If Request(" + chr(34) + "GoBack" + chr(34) + ") = " + chr(34) + "New Query" + chr(34) + " Then")
sp.WriteLine("			Response.Redirect(" + chr(34) + ProjectName + "_filter.asp" + chr(34) + ")")
sp.WriteLine("	End If")
sp.WriteLine("' If there is no sql statement from asp form")
sp.WriteLine("' test for input from same page")
sp.WriteLine("If Request(" + chr(34) + "sql" + chr(34) + ") = " + chr(34) + "" + chr(34) + " Then ' start building sql")
sp.WriteLine("")

' NP is number of pulldowns
NP = objRS2("MaxFields") + 1

sp.WriteLine("")
sp.WriteLine("Dim TheSource(" & NP & "), TheType(" & NP & "), Filter1(" & NP & "), Filter2(" & NP & "), Value1(" & NP & "), Value2(" & NP & "), AndOr(" & NP & ")")
sp.WriteLine("")
sp.WriteLine("TheCount=0")
sp.WriteLine("For I = 1 to " & objRS2("MaxFields"))
sp.WriteLine("")
sp.WriteLine("	TestSource = Request(""frmSource"")(I)")
sp.WriteLine("	If TestSource = """" Then")
sp.WriteLine("		Exit For")
sp.WriteLine("	Else")
sp.WriteLine("		SplitSource=Split(TestSource, ""*"")")
sp.WriteLine("		TheSource(I) = SplitSource(0)")
sp.WriteLine("		TheType(I) = UCASE(SplitSource(1))")
sp.WriteLine("		Filter1(I) = Request(""frmFilter1"")(I)")
sp.WriteLine("		Filter2(I) = Request(""frmFilter2"")(I)")
sp.WriteLine("		Value1(I) = Request(""frmValue1"")(I)")
sp.WriteLine("		Value2(I) = Request(""frmValue2"")(I)")
sp.WriteLine("		AndOr(I) = Request(""frmAndOr"")(I)")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("		TheCount = I")
sp.WriteLine("	End If")
sp.WriteLine("'Response.Write(I)")
sp.WriteLine("Next")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("' make the sql where clause")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("sqlWhere = ""WHERE """)
sp.WriteLine("For I = 1 to TheCount")
sp.WriteLine("WhereHolder1 = """"")
sp.WriteLine("WhereHolder2 = """"")
sp.WriteLine("")
sp.WriteLine("'Response.Write(""The Source is: "" & TheSource(I) & ""<br>"")")
sp.WriteLine("")
sp.WriteLine("' see if there's an and/or clause")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("	If AndOr(I) = """" Then")
sp.WriteLine("		Select Case TheType(I)")
sp.WriteLine("			Case ""N""")
sp.WriteLine("				WhereHolder1 = MakeWhereNum(TheSource(I), Filter1(I), Value1(I))")
sp.WriteLine("			Case ""T""")
sp.WriteLine("				WhereHolder1 = MakeWhereText(TheSource(I), Filter1(I), Value1(I))")
sp.WriteLine("			Case ""D""")
sp.WriteLine("				WhereHolder1 = MakeWhereDate(TheSource(I), Filter1(I), Value1(I))")
sp.WriteLine("		End Select")
sp.WriteLine("")
sp.WriteLine("		If I <> TheCount Then")
sp.WriteLine("			sqlWhere = sqlWhere & "" ("" & WhereHolder1 & "") AND """)
sp.WriteLine("		Else")
sp.WriteLine("			sqlWhere = sqlWhere & "" ("" & WhereHolder1 & "") """)
sp.WriteLine("		End If")
sp.WriteLine("			")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("	Else ' there's an and or or	")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("		Select Case TheType(I)")
sp.WriteLine("			Case ""N""")
sp.WriteLine("				WhereHolder1 = MakeWhereNum(TheSource(I), Filter1(I), Value1(I))")
sp.WriteLine("				WhereHolder2 = MakeWhereNum(TheSource(I), Filter2(I), Value2(I))")
sp.WriteLine("			Case ""T""")
sp.WriteLine("				WhereHolder1 = MakeWhereText(TheSource(I), Filter1(I), Value1(I))")
sp.WriteLine("				WhereHolder2 = MakeWhereText(TheSource(I), Filter2(I), Value2(I))")
sp.WriteLine("			Case ""D""")
sp.WriteLine("				WhereHolder1 = MakeWhereDate(TheSource(I), Filter1(I), Value1(I))")
sp.WriteLine("				WhereHolder2 = MakeWhereDate(TheSource(I), Filter2(I), Value2(I))")
sp.WriteLine("		End Select")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("		If I <> TheCount Then")
sp.WriteLine("			sqlWhere = sqlWhere & "" (("" & WhereHolder1 & "") "" & AndOr(I) & "" ("" & WhereHolder2 & "")) AND """)
sp.WriteLine(" 		Else")
sp.WriteLine("			sqlWhere = sqlWhere & "" (("" & WhereHolder1 & "") "" & AndOr(I) & "" ("" & WhereHolder2& "")) """)
sp.WriteLine("		End If")
sp.WriteLine("			")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("	End If")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("Next")
sp.WriteLine("")

sp.WriteLine("' build a Fields List")

' build the select


rs.Filter = ""
rs.Filter = ("ShowDupes = TRUE")
rs.Sort  = ("ShowDupeOrder")

CountTheFields = rs.RecordCount
TheFields = ""

For I = 1 to CountTheFields

	If objRS2("LinkingField") = rs("TheField") Then
		LinkFieldFlag = TRUE
	End If

	TheFields = TheFields & rs("TheField")

	If I <> CountTheFields Then
		TheFields = TheFields & ", "
	ElseIf LinkFieldFlag = FALSE and RS("LinkingField") <> "" Then
		TheFields = TheFields & ", " & rs("LinkingField")
	End If

rs.MoveNext
Next


sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
TheSQL = "Select " & TheFields & " from " & objRS2("TheTable") & " "
sp.WriteLine(" SQL =" & chr(34) & TheSQL & chr(34) & " & sqlwhere")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("Else")
sp.WriteLine("' create sql")
sp.WriteLine("	sql = Request(""sql"")")
sp.WriteLine("End If")
sp.WriteLine("")

sp.WriteLine("")
sp.WriteLine("dbName = " & chr(34)  & objRS2("TheDB") & chr(34) & " "  & chr(37) + ">")
sp.WriteLine("")
sp.WriteLine("")

sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("<!" & "--#include virtual = ""/thetimes/longrcon.inc"" -->")
sp.WriteLine("")
sp.WriteLine(Chr(60) + Chr(37))


sp.WriteLine("")
sp.WriteLine("'---Limit Records and Page Size")
sp.WriteLine("RS.MaxRecords = maxRecs")
sp.WriteLine("RS.PageSize = DisplayRows 'Number of rows per page")
sp.WriteLine("RS.Open sql, Conn, adOpenStatic, adLockReadOnly, adCmdText")
sp.WriteLine("' get the value of the page and record counts")
sp.WriteLine("' and load them into variables")
sp.WriteLine("TotalPages = RS.PageCount")
sp.WriteLine("TotalRecs = RS.RecordCount")
sp.WriteLine("' The test sees if there is a value to pick")
sp.WriteLine("' up from the buttons for prior and next page")
sp.WriteLine("' If there is no value, it sets the PageNumber to 1")
sp.WriteLine("ScrollAction = Request(""ScrollAction"")")
sp.WriteLine("if ScrollAction <> """" Then")
sp.WriteLine("	PageNo = ScrollAction")
sp.WriteLine("	if PageNo < 1 Then ")
sp.WriteLine("		PageNo = 1")
sp.WriteLine("	end if")
sp.WriteLine("else")
sp.WriteLine("	PageNo = 1")
sp.WriteLine("end if")
sp.WriteLine("' if any records returned tell the recordset")
sp.WriteLine("' which page you want displayed")
sp.WriteLine("If Not RS.EOF Then")
sp.WriteLine("	RS.AbsolutePage = PageNo")
sp.WriteLine("End If")
sp.WriteLine(chr(37) & ">")
sp.WriteLine("<HTML>")
sp.WriteLine("<HEAD>")
sp.WriteLine("<TITLE>Query Results Page</TITLE>")
sp.WriteLine("<style>")
sp.WriteLine("<!--")
sp.WriteLine("th           { background-color: #0000FF; color: #D9FFFF; font-size: 8pt }")
sp.WriteLine("td           { background-color: #FFFFFF; font-size: 8pt }")
sp.WriteLine("-->")
sp.WriteLine("</style>")
sp.WriteLine("</HEAD>")
sp.WriteLine("<body bgcolor=""#FFFFFF"">")
sp.WriteLine("<!" & "--#include file = """ & ProjectName & "_links.inc"" -->")
sp.WriteLine(Chr(60) + Chr(37))

sp.WriteLine("' creates a form and ")
sp.WriteLine("' loads the value of sql into a hidden ")
sp.WriteLine("' input type called SQL")

sp.WriteLine(chr(37) & ">")

sp.WriteLine("	<FORM METHOD=POST ACTION=""" & ProjectName & "_filterresults.asp"">")

' The following line is screwed up steal from mpd

sp.WriteLine("	<INPUT TYPE=" + chr(34) + "HIDDEN" + chr(34) + " NAME=" + chr(34) + "sql" + chr(34) + " VALUE=" + chr(34) + "<" + Chr(37) + " = sql " + Chr(37) + ">" + chr(34) + ">")

sp.WriteLine(Chr(60) + Chr(37))
sp.WriteLine("' Display the page you are on")
sp.WriteLine("' display the total # of records")
sp.WriteLine("' and if you are maxed out")
sp.WriteLine(" If Not RS.EOF Then")
sp.WriteLine(Chr(37) + Chr(62))
sp.WriteLine("<H3>" & objRS2("ProjectAlias") & " Filter Search Results</H3>")
sp.WriteLine("<B>Page <" + Chr(37) + "=PageNo" + Chr(37) + "> of <" + Chr(37) + "=TotalPages" + Chr(37) + "></B> [Total records: <" + Chr(37) + "=TotalRecs" + Chr(37) + ">")
sp.WriteLine("<" + Chr(37) + "	If TotalRecs = MaxRecs Then")
sp.WriteLine("		Response.Write(" + chr(34) + " (the max allowed.)]" + chr(34) + ")")
sp.WriteLine("	else")
sp.WriteLine("		Response.Write(" + chr(34) + "]" + chr(34) + ")")
sp.WriteLine("	End If " + Chr(37) + ">")
sp.WriteLine("<P>")
If Lfield <> "" Then
	sp.WriteLine("<center><small><b>Click on (p) to see a printable version of the complete record.</b></small></center>")
End If
sp.WriteLine("<div align=" + chr(34) + "center" + chr(34) + "><center>")
sp.WriteLine("<table border=" + chr(34) + "1" + chr(34) + ">")
sp.WriteLine("  <tr>")
rs.MoveFirst
For I = 1 to CountTheFields
	sp.WriteLine("    <th>" + rs("FieldAlias") + "</th>")
	rs.MoveNext
Next
sp.WriteLine("  </tr>")
sp.WriteLine(Chr(60) + Chr(37))
sp.WriteLine("' initialize the row count and start the")
sp.WriteLine("' do while loop to print this page of records")
sp.WriteLine("	RowCount = rs.PageSize")
sp.WriteLine(" Do While Not RS.EOF and RowCount > 0" + Chr(37) + ">")
sp.WriteLine("  <tr>")
rs.MoveFirst
For I = 1 to CountTheFields
	If objRS2("LinkingField") <> "" and I = 1 Then
		sp.WriteLine("    <td><" + Chr(37) + " = rs(" + chr(34) + rs("TheField") + chr(34) + ") " + Chr(37) + ">")
		sp.WriteLine("    <a href=""" & ProjectName & "_profile.asp?" & objRS2("LinkingField") & "=<" & chr(37) + " = rs(" + chr(34) + LField + chr(34) + ") " + Chr(37) + ">" + chr(34) & "> (p)</a></td>")


	Else
		sp.WriteLine("    <td><" + Chr(37) + " = rs(" + chr(34) + RS("TheField") + chr(34) + ") " + Chr(37) + ">&nbsp;</td>")

	End If
rs.MoveNext
Next
sp.WriteLine("  </tr>")
sp.WriteLine(Chr(60) + Chr(37))
sp.WriteLine("' decrease the value of RowCount by 1")
sp.WriteLine("	RowCount = RowCount - 1")
sp.WriteLine("	RS.MoveNext")
sp.WriteLine("Loop")
sp.WriteLine(Chr(37) + Chr(62))
sp.WriteLine("</TABLE>")
sp.WriteLine("</div></center>")
sp.WriteLine("</p>")
sp.WriteLine(Chr(60) + Chr(37))
sp.WriteLine("' create prior next buttons")
sp.WriteLine("if TotalPages > 1 then " + Chr(37) + ">")
sp.WriteLine("<Strong>Pages: </Strong>")
sp.WriteLine("	<" + Chr(37) + " For I = 1 to TotalPages")
sp.WriteLine("	   if CInt(PageNo) <> I Then " + Chr(37) + ">")
sp.WriteLine("	<INPUT TYPE=SUBMIT NAME=ScrollAction VALUE=" + Chr(34) + "<" + Chr(37) + " = I " + Chr(37) + ">" + chr(34) + ">")
sp.WriteLine("	<" & chr(37) & " else " & chr(37) & ">")
sp.WriteLine("	<b><" & chr(37) & " = I " & chr(37) & "></b>")
sp.WriteLine("	<" + Chr(37) + " end if ")
sp.WriteLine("  Next ")
sp.WriteLine(" end if " + Chr(37) + ">") 
sp.WriteLine("<" + Chr(37) + " ")
sp.WriteLine("'----------------------------------------------")
sp.WriteLine("'		If No results")
sp.WriteLine("'----------------------------------------------")
sp.WriteLine("Else " + Chr(37) + ">")
sp.WriteLine("	<h3>Your query returned no data.<br></h3>")
sp.WriteLine(" ")
sp.WriteLine("<" + Chr(37) + " End If " + Chr(37) + ">")
sp.WriteLine("<INPUT TYPE=" + chr(34) + "SUBMIT" + chr(34) + " NAME = " + chr(34) + "GoBack" + chr(34) + " VALUE = " + chr(34) + "New Query" + chr(34) + ">")
sp.WriteLine(Chr(60) + Chr(37))
sp.WriteLine("rs.Close")
sp.WriteLine("conn.Close")
sp.WriteLine("set rs = nothing")
sp.WriteLine("set Conn = nothing")
sp.WriteLine(Chr(37) + Chr(62))
sp.WriteLine("<p align=" + chr(34) + "center" + chr(34) + "><em>This page was generated by a web application developed by Tom Torok of The New York Times.<br>")
sp.WriteLine("<a href=" + chr(34) + "mailto:tomtorok@nytimes.com" + chr(34) + ">Comments</a></em></p>")
sp.WriteLine("</FORM>")
sp.WriteLine("</BODY>")
sp.WriteLine("</HTML>")

sp.WriteLine("<" & chr(37))

sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("'Response.Write(""The where clause is: "" & sqlWhere & ""<br>"")")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("Function MakeWhereNum(TheFieldName, TheOperator, TheValue)")
sp.WriteLine("")
sp.WriteLine("Select Case TheOperator")
sp.WriteLine("	Case ""eq""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" = "" & TheValue")
sp.WriteLine("	Case ""noteq""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" <> "" & TheValue")
sp.WriteLine("	Case ""gt""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" > "" & TheValue")
sp.WriteLine("	Case ""gtet""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" >= "" & TheValue")
sp.WriteLine("	Case ""lt""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" < "" & TheValue")
sp.WriteLine("	Case ""ltet""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" <= "" & TheValue")
sp.WriteLine("	Case ""bw""")
sp.WriteLine("		MakeWhereNum = "" Cast("" & TheFieldName & "" as varchar(25)) Like '"" & TheValue & ""%'""")
sp.WriteLine("	Case ""dnbw""")
sp.WriteLine("		MakeWhereNum = "" Cast("" & TheFieldName & "" as varchar(25)) NOT Like '"" & TheValue & ""%'""")
sp.WriteLine("	Case ""ew""")
sp.WriteLine("		MakeWhereNum = "" Cast("" & TheFieldName & "" as varchar(25)) Like '%"" & TheValue & ""'""")
sp.WriteLine("	Case ""dnew""")
sp.WriteLine("		MakeWhereNum = "" Cast("" & TheFieldName & "" as varchar(25)) NOT Like '%"" & TheValue & ""'""")
sp.WriteLine("	Case ""con""")
sp.WriteLine("		MakeWhereNum = "" Cast("" & TheFieldName & "" as varchar(25)) Like '%"" & TheValue & ""%'""")
sp.WriteLine("	Case ""dncon""")
sp.WriteLine("		MakeWhereNum = "" Cast("" & TheFieldName & "" as varchar(25)) NOT Like '%"" & TheValue & ""%'""")
sp.WriteLine("	Case ""blank""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" is null """)
sp.WriteLine("	Case ""notblank""")
sp.WriteLine("		MakeWhereNum = "" "" & TheFieldName & "" is NOT null  "" ")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("End Select")
sp.WriteLine("")
sp.WriteLine("End Function")
sp.WriteLine("")
sp.WriteLine("Function MakeWhereText(TheFieldName, TheOperator, TheValue)")
sp.WriteLine("If InStr(TheValue, ""'"") Then")
sp.WriteLine("	TheValue = Replace(TheValue, ""'"", ""''"")")
sp.WriteLine("End If")
sp.WriteLine("Select Case TheOperator")
sp.WriteLine("	Case ""eq""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" = '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereText, ""]"") and InStr(MakeWhereText, ""["") Then")
sp.WriteLine("			MakeWhereText = Replace(MakeWhereText, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""noteq""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" <> '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereText, ""]"") and InStr(MakeWhereText, ""["") Then")
sp.WriteLine("			MakeWhereText = Replace(MakeWhereText, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""gt""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" > '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereText, ""]"") and InStr(MakeWhereText, ""["") Then")
sp.WriteLine("			MakeWhereText = Replace(MakeWhereText, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""gtet""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" >=  '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereText, ""]"") and InStr(MakeWhereText, ""["") Then")
sp.WriteLine("			MakeWhereText = Replace(MakeWhereText, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""lt""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" <  '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereText, ""]"") and InStr(MakeWhereText, ""["") Then")
sp.WriteLine("			MakeWhereText = Replace(MakeWhereText, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""ltet""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" <= '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereText, ""]"") and InStr(MakeWhereText, ""["") Then")
sp.WriteLine("			MakeWhereText = Replace(MakeWhereText, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""bw""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" Like '"" & TheValue & ""%'""")
sp.WriteLine("	Case ""dnbw""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" NOT Like '"" & TheValue & ""%'""")
sp.WriteLine("	Case ""ew""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" Like '%"" & TheValue & ""'""")
sp.WriteLine("	Case ""dnew""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" NOT Like '%"" & TheValue & ""'""")
sp.WriteLine("	Case ""con""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" Like '%"" & TheValue & ""%'""")
sp.WriteLine("	Case ""dncon""")
sp.WriteLine("		MakeWhereText = "" "" & TheFieldName & "" NOT Like '%"" & TheValue & ""%'""")
sp.WriteLine("	Case ""blank""")
sp.WriteLine("		MakeWhereText = "" ("" & TheFieldName & "" is Null or "" & TheFieldName & "" = '') """)
sp.WriteLine("	Case ""notblank""")
sp.WriteLine("		MakeWhereText = "" ("" & TheFieldName & "" is NOT Null and "" & TheFieldName & "" <> '') """)
sp.WriteLine("End Select")
sp.WriteLine("")
sp.WriteLine("End Function")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("Function MakeWhereDate(TheFieldName, TheOperator, TheValue)")
sp.WriteLine("")
sp.WriteLine("")
sp.WriteLine("Select Case TheOperator")
sp.WriteLine("	Case ""eq""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" = '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereDate, ""]"") and InStr(MakeWhereDate, ""["") Then")
sp.WriteLine("			MakeWhereDate = Replace(MakeWhereDate, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""noteq""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" <> '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereDate, ""]"") and InStr(MakeWhereDate, ""["") Then")
sp.WriteLine("			MakeWhereDate = Replace(MakeWhereDate, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""gt""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" > '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereDate, ""]"") and InStr(MakeWhereDate, ""["") Then")
sp.WriteLine("			MakeWhereDate = Replace(MakeWhereDate, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""gtet""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" >=  '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereDate, ""]"") and InStr(MakeWhereDate, ""["") Then")
sp.WriteLine("			MakeWhereDate = Replace(MakeWhereDate, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""lt""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" <  '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereDate, ""]"") and InStr(MakeWhereDate, ""["") Then")
sp.WriteLine("			MakeWhereDate = Replace(MakeWhereDate, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""ltet""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" <= '"" & TheValue & ""'""")
sp.WriteLine("		If InStr(MakeWhereDate, ""]"") and InStr(MakeWhereDate, ""["") Then")
sp.WriteLine("			MakeWhereDate = Replace(MakeWhereDate, ""'"", """")")
sp.WriteLine("		End If")
sp.WriteLine("	Case ""bw""")
sp.WriteLine("		MakeWhereDate = "" Cast("" & TheFieldName & "" as varchar(25)) Like '"" & TheValue & ""%'""")
sp.WriteLine("	Case ""dnbw""")
sp.WriteLine("		MakeWhereDate = "" Cast("" & TheFieldName & "" as varchar(25)) NOT Like '"" & TheValue & ""%'""")
sp.WriteLine("	Case ""ew""")
sp.WriteLine("		MakeWhereDate = "" Cast("" & TheFieldName & "" as varchar(25)) Like '%"" & TheValue & ""'""")
sp.WriteLine("	Case ""dnew""")
sp.WriteLine("		MakeWhereDate = "" Cast("" & TheFieldName & "" as varchar(25)) NOT Like '%"" & TheValue & ""'""")
sp.WriteLine("	Case ""con""")
sp.WriteLine("		MakeWhereDate = "" Cast("" & TheFieldName & "" as varchar(25)) Like '%"" & TheValue & ""%'""")
sp.WriteLine("	Case ""dncon""")
sp.WriteLine("		MakeWhereDate = "" Cast("" & TheFieldName & "" as varchar(25)) NOT Like '%"" & TheValue & ""%'""")
sp.WriteLine("	Case ""blank""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" is NULL "" ")
sp.WriteLine("	Case ""notblank""")
sp.WriteLine("		MakeWhereDate = "" "" & TheFieldName & "" is NOT NULL "" ")
sp.WriteLine("")
sp.WriteLine("End Select")
sp.WriteLine("")
sp.WriteLine("End Function")
sp.WriteLine("")

sp.WriteLine(chr(37) & ">")



sp.Close


' -----------------------------  drill down page


